language: android
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-22
  - android-21
script:
- "./gradlew assembleDebug"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: F7nsl+PghiCrMm35KKraQHAUu+y8ZhiZ0zHJYKZpbxTYyELNjsyHhnvunGLzfnHvDm2i/GOW0cUe86iAH5V6w/dSxoOjhNmTaqfl4TDdow+X7PS0f+zRdL7G5TqHb+TC748gw8kkKYmZDplRxJhiaWG419S8VjAp2C/JgJk7/gOa04IQataWGdoALBUSYEalm9yv8mgz/6PglMuodWNPVXrSUftChbUW5kCvtQNAh8CkO5cEx4KnPwngcMgpvXuC8MWuA4h8+Q9mSKq4eGMs4vJuubo0keWvWM+9GpKUQObcu2JJpWsqZx44YlLcYW1sKTFIbxSuCVzHxU6WvqaQw6NDlCjvg76+0mFiqIpGkUuo48KlqYkG6xKEMPLXw5i8XDuEs2VVin3Dg0ndLcVYXCtt7ezzJXhrboMmIR4i7VB2FpBEU0N8bsNZdypmAz3NnPBBo/ResUUlVTHELREEglyXWwtFN2KIoHJtkZm2y8ijIcS5PJtcQzh7dNMV+/9uH6nVs2z+W1qkXXYfayPoLOYFQcGJ1osQZH9OymOc0AjjyBOI+cvv6UrLARHoEp54/Z9nGv2gc3TvXO3bjGmnynoGCJsYW1nlOxW46HTpS01k0rJ2nHwPaLuzr1bOc2yLf+/aZ2JdwFd41MYjo0LvmELXsotrnmy44slfF1+ULSE=
  file: app/build/outputs/apk/app-debug.apk
  on:
    repo: queler/holokenmod
    all_branches: true

